### ISSUE TITLE
Save image urls to its own table; display images in history screen

### ISSUE THREAD

**Issue by lydavid** [lydavid/MusicSearch#237]
mbid to image url table

`mbid`
`image_path` Either cover art archive or Spotify

Then we can use this to display images in history and search

## TODO

- [x] create table
- [x] migrate release and release group cover arts
  - [x] we originally trimmed  `.jpg`, but [CAA](https://musicbrainz.org/doc/How_to_Add_Cover_Art) supports gif, jpg, jpeg, png, htm, html, jpe, jfif and pdf
- [x] delete release and release group cover art column
- [x] Note that we are not currently storing the spotify image url, so we always have to make an additional GET call to Spotify. With this change, let's store the artist image url, so only coil has to do a call

## Notes

https://developer.spotify.com/documentation/web-api/reference/get-an-artist
Spotify image url looks like: https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228

## Continuation

- [ ] #276
