### ISSUE TITLE
replace hilt and dagger with koin for multiplatform DI

### ISSUE THREAD

**Issue by lydavid** [lydavid/MusicSearch#407]
search `kapt(libs.hilt.android.compiler)`

## options
- https://github.com/kosi-libs/Kodein
- [x] https://github.com/InsertKoinIO/koin (leaning towards this due to popularity)
- https://github.com/evant/kotlin-inject (compile-time safety)

## issue related to generics
- lack of generic support for `PagedList`
  - https://insert-koin.io/docs/reference/koin-core/definitions/#dealing-with-generics

With dagger/hilt, we had:
```kt
class PagedList<RM : RoomModel, LI : ListItemModel> @Inject constructor() : IPagedList<LI>
```

The equivalent with koin:
```kt
@Single
class PagedList<RM : RoomModel, LI : ListItemModel> : IPagedList<LI>
```

but this gives us this error:
> Not enough information to infer type variable RM

app now runs but will crash on any screen that requires `PagedList`, which is most of our screens

Two choices:
- wait for generic support
- [x] refactor to inject an intermediary factory class inherits PagedList with the appropriate types

## Todo
- [x] remove dagger/hilt from all gradle modules and toml
- [x] test: https://insert-koin.io/docs/reference/koin-test/testing/
- [x] instrument test: https://insert-koin.io/docs/reference/koin-android/instrumented-testing/
  - compared to before with hilt, it seems like our test database is persisting between runs?
  - previously, we had a hiltTestRule, but our current koinTestRule doesn't work, so we're using a TestApplication, so maybe this causes it to persist
  - [x] either nuke tables after every run (can be a test rule) or get koinTestRule  working
  - [x] hasRelations consistently fails when running all tests but not when running a single test class. Something must be persisting
    - when I observed it, it was showing a spinner but never progressing
    - turns out it's because I had `RelationsList` as a singleton rather than a factory
- [ ] #437
  - [x] use include: https://insert-koin.io/docs/reference/koin-core/modules#module-includes-since-32
  - should everything be in `data-android`?
  - or should they be in their own module?
- [x] ApplicationScope needed?
  - no, it was a qualifier to disambiguate CoroutineScope: https://medium.com/androiddevelopers/create-an-application-coroutinescope-using-hilt-dd444e721528
- [ ] #438

### Make sure to use kspAndroidTest for the compiler!
Interestingly, our tests would still run albeit extremely slow without it.

### Why some components are singleton and others are factory.
With dagger, I didn't really think about non-singleton (those not marked with `@Singleton`). But those are in fact just factories (a new instance is created each time it's requested). With koin, I had to explicitly define these as `factory`. A few times, I had them as `single` at first, only to find out a screen always loads the same data as another similar screen a visited (eg. an artist's relationships appeared in every other artist's page).

In particular, it's my UI-related classes that need to be a factory. eg. RelationsList, CollectionPagedList
This has burned me many times, especially during UI tests.
On the bright side, by persisting koin through the entire UI test suite, I was able to catch this problem.

### JUnit test rules
I never took the time to looking into their implementations. They just allow executing some code before/after every test.
